version: "3.8"

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: cmcfm2a6r0003nxadea86nal8
      PMA_USER: cmcfm2a6o0001adnx22xa37zj
      PMA_PASSWORD: eZ0BJlZtZfkmnqS6ERfH4dJP
    labels:
      - "coolify.url=phpMyAdmin.quattrogcc.ae"
      - "coolify.port=80"
    networks:
      - coolify  # ← اضف دي

networks:
  coolify:
    external: true
