version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: cmcg4jh57002xnxadk7zp2p8x-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_sports
      MYSQL_USER: db_sports
      MYSQL_PASSWORD: db_sports_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # لو هتربط من برة (مثلاً بـ MySQL Workbench)
    networks:
      - coolify

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: db_sports
      PMA_PASSWORD: db_sports_password
    ports:
      - "8080:80"  # تفتح المتصفح على http://ip:8080
    depends_on:
      - mariadb
    networks:
      - coolify

volumes:
  db_data:

networks:
  coolify:
    external: true
